### PR TITLE
Extract simplex

### PR DESCRIPTION
**Pull request by numberoverzero**
The 2.0.0 release removes `plugins/router.py` and the `simplex` dependency.  Although probably not used anywhere, `bottom.plugins.router.Router` was part of the public API and so a major version change is required.

Aside from merge conflicts, this should simplify the work in #36.

Additionally:

* The `bottom/examples/` folder uses a shared `common.py` to configure a client and attach the standard event handlers `client_connect` and `ping`.
* In place of the `simplex` router, the `Extensions` section of the User Guide provides a regex-based `Router` (which is just `s/simplex/re/` the original router).
* Touch up README, sample code for readability.

### CODE REVIEW

**Comment by numberoverzero** [comment]
Your thoughts, @miedzinski?

**Comment by miedzinski** [comment]
I really like it. Good job!

**Comment by numberoverzero** [comment]
Thanks!  Are you up for resolving merge conflicts on #36, or do you want me to give it a try?

**Comment by miedzinski** [comment]
I'll fix it.

**Pull request merged**
