### PR TITLE
some doc fixes

### PR DESCRIPTION
**Pull request by Yay295**

### CODE REVIEW

**Comment by Yay295** [comment]
For the ping and pong examples, should `# server2 requires server1` be `# server1 requires server2`, or should `client.send('PING', server2='tolsun.oulu.fi')` be `client.send('PING', server1='tolsun.oulu.fi')`?

**Comment by numberoverzero** [comment]
Thanks for the PR!

I'm not sure about the PING question; that looks like something that came from the RFC example and got mangled.  It's almost certainly wrong but I haven't read the spec in some time.  Any ideas?

**Comment by Yay295** [comment]
Actually, I got that wrong. `JOIN 0` *does* make you leave all channels, as silly as that sounds.
I know how PING works now, but I'm still not quite sure how you would use a PONG, other than to reply to a PING.

**Comment by Yay295** [comment]
I suppose if I were `PING Yay295`ed, I could `PONG numberoverzero irc.github.com` you (if I'm understanding it correctly), but I don't know why I would want to do that.

Actually...

If we were on different servers and you `PING Yay295 myserver`ed me, I would have to `PONG numberoverzero yourserver` you. I think.

**Comment by numberoverzero** [comment]
> If we were on different servers and you PING Yay295 myservered me, I would have to PONG numberoverzero yourserver you. I think.

I believe this is correct, yes.

> JOIN 0 does make you leave all channels, as silly as that sounds.

I decided to look up 3.2.1 to verify because this sounds so strange (even though I wrote that comment!) so for any future readers, in fact this is correct:

> > Note that this message accepts a special argument ("0"), which is
   a special request to leave all channels the user is currently a member
   of.  The server will process this message as if the user had sent
   a PART command (See Section 3.2.2) for each channel he is a member
   of.

**Comment by Yay295** [comment]
I tried pinging a different server using this library and Hexchat, but I just got a `401 ERR_NOSUCHNICK` response in Hexchat, and nothing in Python, so even if that is how it's supposed to work it doesn't seem well supported.

**Comment by numberoverzero** [comment]
Thanks for your persistence, glad to see this change make it in!  There are a few dangling items but since they're part of larger stories I think we can address them in another PR:

* [ ] Update docs to mention deviation from rfc2812
* [ ] Version bump for breaking change in params
* [ ] CHANGELOG mention
* [ ] Update docs for new params

I'm going to hold off on a new PyPI release to batch up the other PRs and doc improvements.  Thanks again 🚀

**Pull request merged**
